# Base configs
baseurl: "https://photography.rampatra.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Banipreet"
subtitle: "See the world through my eyes!"
author: "Banipreet"
header:
 title: "Photography"
 subtitle: "by Banipreet"
footer:
 name: "Hey there, my name is Banipreet"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/banipreet.raheja/"
  twitter: "https://twitter.com/bani_raheja"
  instagram: "https://www.instagram.com/banipreet_raheja"
  linkedin: "https://in.linkedin.com/in/banipreet-raheja"
  github: "https://www.github.com/banipreetr"

theme: jekyll-theme-cayman